apiVersion: v1
kind: Service
metadata:
  name: ispmonitor-api
  namespace: ispmonitor
  labels:
    app: ispmonitor-api
    app.kubernetes.io/name: ispmonitor
    app.kubernetes.io/component: api
spec:
  selector:
    app: ispmonitor-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: ispmonitor-poller
  namespace: ispmonitor
  labels:
    app: ispmonitor-poller
    app.kubernetes.io/name: ispmonitor
    app.kubernetes.io/component: poller
spec:
  selector:
    app: ispmonitor-poller
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
