apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ispmonitor

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: ispmonitor-api
  - patch: |-
      - op: replace
        path: /data/DEPLOYMENT_MODE
        value: development
      - op: replace
        path: /data/LOG_LEVEL
        value: debug
    target:
      kind: ConfigMap
      name: ispmonitor-config

images:
  - name: ghcr.io/mohamadkhaledabbas/ispvisualmonitor
    newTag: develop
